export type Option = {
  value: string;
  label: string;
};

export const currentLocationCountryOptions: Option[] = [
  { value: 'AFGH', label: 'AFGHANISTAN' },
  { value: 'ALBA', label: 'ALBANIA' },
  { value: 'ALGE', label: 'ALGERIA' },
  { value: 'ASAM', label: 'AMERICAN SAMOA' },
  { value: 'ANDO', label: 'ANDORRA' },
  { value: 'ANGA', label: 'ANGOLA' },
  { value: 'ARGE', label: 'ARGENTINA' },
  { value: 'ARME', label: 'ARMENIA' },
  { value: 'AUST', label: 'AUSTRIA' },
  { value: 'AZER', label: 'AZERBAIJAN' },
  { value: 'BDES', label: 'BANGLADESH' },
  { value: 'BELM', label: 'BELGIUM' },
  { value: 'BRAZ', label: 'BRAZIL' },
  { value: 'BULG', label: 'BULGARIA' },
  { value: 'CAMB', label: 'CAMBODIA' },
  { value: 'CANA', label: 'CANADA' },
  { value: 'CHIL', label: 'CHILE' },
  { value: 'PRCH', label: 'CHINA' },
  { value: 'COLA', label: 'COLOMBIA' },
  { value: 'CROA', label: 'CROATIA' },
  { value: 'CZEH', label: 'CZECHIA (CZECH REP)' },
  { value: 'DENM', label: 'DENMARK' },
  { value: 'EGYP', label: 'EGYPT' },
  { value: 'ENGL', label: 'ENGLAND' },
  { value: 'ESTO', label: 'ESTONIA' },
  { value: 'ETHI', label: 'ETHIOPIA' },
  { value: 'FIJI', label: 'FIJI' },
  { value: 'FINL', label: 'FINLAND' },
  { value: 'FRAE', label: 'FRANCE' },
  { value: 'GEOG', label: 'GEORGIA' },
  { value: 'GERM', label: 'GERMANY' },
  { value: 'GHAN', label: 'GHANA' },
  { value: 'GREE', label: 'GREECE' },
  { value: 'GUAT', label: 'GUATEMALA' },
  { value: 'HAIT', label: 'HAITI' },
  { value: 'HKON', label: 'HONG KONG SAR' },
  { value: 'HUNG', label: 'HUNGARY' },
  { value: 'ICEL', label: 'ICELAND' },
  { value: 'INDI', label: 'INDIA' },
  { value: 'INDO', label: 'INDONESIA' },
  { value: 'IRAN', label: 'IRAN' },
  { value: 'IRAQ', label: 'IRAQ' },
  { value: 'IREP', label: 'IRELAND' },
  { value: 'ISRA', label: 'ISRAEL' },
  { value: 'ITAL', label: 'ITALY' },
  { value: 'JAPA', label: 'JAPAN' },
  { value: 'JORD', label: 'JORDAN' },
  { value: 'KAZA', label: 'KAZAKHSTAN' },
  { value: 'KENY', label: 'KENYA' },
  { value: 'SKOR', label: 'KOREA, SOUTH' },
  { value: 'KUWA', label: 'KUWAIT' },
  { value: 'LAOS', label: 'LAO PEOPLES DEM REP' },
  { value: 'LATV', label: 'LATVIA' },
  { value: 'LEBA', label: 'LEBANON' },
  { value: 'LITH', label: 'LITHUANIA' },
  { value: 'LUXE', label: 'LUXEMBOURG' },
  { value: 'MALS', label: 'MALAYSIA' },
  { value: 'MALT', label: 'MALTA' },
  { value: 'MEXI', label: 'MEXICO' },
  { value: 'MONG', label: 'MONGOLIA' },
  { value: 'MORO', label: 'MOROCCO' },
  { value: 'MYAN', label: 'MYANMAR' },
  { value: 'NEPA', label: 'NEPAL' },
  { value: 'NETH', label: 'NETHERLANDS' },
  { value: 'NZEA', label: 'NEW ZEALAND' },
  { value: 'NIGR', label: 'NIGER' },
  { value: 'NGRA', label: 'NIGERIA' },
  { value: 'NORW', label: 'NORWAY' },
  { value: 'OMAN', label: 'OMAN' },
  { value: 'PKSN', label: 'PAKISTAN' },
  { value: 'PANA', label: 'PANAMA' },
  { value: 'PERU', label: 'PERU' },
  { value: 'PHIL', label: 'PHILIPPINES' },
  { value: 'POLA', label: 'POLAND' },
  { value: 'PORL', label: 'PORTUGAL' },
  { value: 'QATA', label: 'QATAR' },
  { value: 'ROUM', label: 'ROMANIA' },
  { value: 'RFED', label: 'RUSSIAN FEDERATION' },
  { value: 'SAAR', label: 'SAUDI ARABIA' },
  { value: 'SCOT', label: 'SCOTLAND' },
  { value: 'SENE', label: 'SENEGAL' },
  { value: 'SERB', label: 'SERBIA' },
  { value: 'SING', label: 'SINGAPORE' },
  { value: 'SVKA', label: 'SLOVAK REPUBLIC' },
  { value: 'SLOV', label: 'SLOVENIA' },
  { value: 'SAFR', label: 'SOUTH AFRICA' },
  { value: 'SPAI', label: 'SPAIN' },
  { value: 'SRIL', label: 'SRI LANKA' },
  { value: 'SUDA', label: 'SUDAN' },
  { value: 'SWED', label: 'SWEDEN' },
  { value: 'SWIT', label: 'SWITZERLAND' },
  { value: 'SYRI', label: 'SYRIA' },
  { value: 'TAIW', label: 'TAIWAN' },
  { value: 'TANZ', label: 'TANZANIA' },
  { value: 'THAI', label: 'THAILAND' },
  { value: 'TUNI', label: 'TUNISIA' },
  { value: 'TURE', label: 'TURKIYE' },
  { value: 'UAEM', label: 'UNITED ARAB EMIRATES' },
  { value: 'UK', label: 'UNITED KINGDOM' },
  { value: 'USA', label: 'UNITED STATES' },
  { value: 'URUG', label: 'URUGUAY' },
  { value: 'UZBE', label: 'UZBEKISTAN' },
  { value: 'VENE', label: 'VENEZUELA' },
  { value: 'VIET', label: 'VIETNAM' },
  { value: 'WALE', label: 'WALES' },
  { value: 'YEME', label: 'YEMEN' },
  { value: 'ZAMB', label: 'ZAMBIA' },
  { value: 'ZIMB', label: 'ZIMBABWE' }
];

export const legalStatusOptions: Option[] = [
  { value: 'citizen', label: 'Citizen' },
  { value: 'permanent-resident', label: 'Permanent Resident' },
  { value: 'visitor', label: 'Visitor' },
  { value: 'student', label: 'Student' },
  { value: 'work-visa', label: 'Work Visa' },
  { value: 'no-legal-status', label: 'No Legal Status' },
  { value: 'other', label: 'Other' }
];

export const reasonForVisitingAustraliaOptions: Option[] = [
  { value: 'business', label: 'Business' },
  { value: 'tourism', label: 'Tourism' },
  { value: 'family-visit', label: 'Family visit' },
  { value: 'study', label: 'Study' },
  { value: 'religious-event', label: 'Religious event' },
  { value: 'other', label: 'Other' }
];
